#pragma once
#include <QPair>
#include <QString>
#include <QVector>

inline const QVector<QPair<QString, QString>> EMOJIS = {
    {QStringLiteral("😀"), QStringLiteral("grinning face")},
    {QStringLiteral("😃"), QStringLiteral("grinning face with big eyes")},
    {QStringLiteral("😄"), QStringLiteral("grinning face with smiling eyes")},
    {QStringLiteral("😁"), QStringLiteral("beaming face with smiling eyes")},
    {QStringLiteral("😆"), QStringLiteral("grinning squinting face")},
    {QStringLiteral("😅"), QStringLiteral("grinning face with sweat")},
    {QStringLiteral("🤣"), QStringLiteral("rolling on the floor laughing")},
    {QStringLiteral("😂"), QStringLiteral("face with tears of joy")},
    {QStringLiteral("🙂"), QStringLiteral("slightly smiling face")},
    {QStringLiteral("🙃"), QStringLiteral("upside-down face")},
    {QStringLiteral("😉"), QStringLiteral("winking face")},
    {QStringLiteral("😊"), QStringLiteral("smiling face with smiling eyes")},
    {QStringLiteral("😇"), QStringLiteral("smiling face with halo")},
    {QStringLiteral("🥰"), QStringLiteral("smiling face with hearts")},
    {QStringLiteral("😍"), QStringLiteral("smiling face with heart-eyes")},
    {QStringLiteral("🤩"), QStringLiteral("star-struck")},
    {QStringLiteral("😘"), QStringLiteral("face blowing a kiss")},
    {QStringLiteral("😗"), QStringLiteral("kissing face")},
    {QStringLiteral("😚"), QStringLiteral("kissing face with closed eyes")},
    {QStringLiteral("😙"), QStringLiteral("kissing face with smiling eyes")},
    {QStringLiteral("🥲"), QStringLiteral("smiling face with tear")},
    {QStringLiteral("😋"), QStringLiteral("face savoring food")},
    {QStringLiteral("😛"), QStringLiteral("face with tongue")},
    {QStringLiteral("😜"), QStringLiteral("winking face with tongue")},
    {QStringLiteral("🤪"), QStringLiteral("zany face")},
    {QStringLiteral("😝"), QStringLiteral("squinting face with tongue")},
    {QStringLiteral("🤑"), QStringLiteral("money-mouth face")},
    {QStringLiteral("🤗"), QStringLiteral("smiling face with open hands")},
    {QStringLiteral("🤭"), QStringLiteral("face with hand over mouth")},
    {QStringLiteral("🤫"), QStringLiteral("shushing face")},
    {QStringLiteral("🤔"), QStringLiteral("thinking face")},
    {QStringLiteral("🤐"), QStringLiteral("zipper-mouth face")},
    {QStringLiteral("🤨"), QStringLiteral("face with raised eyebrow")},
    {QStringLiteral("😐"), QStringLiteral("neutral face")},
    {QStringLiteral("😑"), QStringLiteral("expressionless face")},
    {QStringLiteral("😶"), QStringLiteral("face without mouth")},
    {QStringLiteral("😏"), QStringLiteral("smirking face")},
    {QStringLiteral("😒"), QStringLiteral("unamused face")},
    {QStringLiteral("🙄"), QStringLiteral("face with rolling eyes")},
    {QStringLiteral("😬"), QStringLiteral("grimacing face")},
    {QStringLiteral("🤥"), QStringLiteral("lying face")},
    {QStringLiteral("😌"), QStringLiteral("relieved face")},
    {QStringLiteral("😔"), QStringLiteral("pensive face")},
    {QStringLiteral("😪"), QStringLiteral("sleepy face")},
    {QStringLiteral("🤤"), QStringLiteral("drooling face")},
    {QStringLiteral("😴"), QStringLiteral("sleeping face")},
    {QStringLiteral("😷"), QStringLiteral("face with medical mask")},
    {QStringLiteral("🤒"), QStringLiteral("face with thermometer")},
    {QStringLiteral("🤕"), QStringLiteral("face with head-bandage")},
    {QStringLiteral("🤢"), QStringLiteral("nauseated face")},
    {QStringLiteral("🤮"), QStringLiteral("face vomiting")},
    {QStringLiteral("🤧"), QStringLiteral("sneezing face")},
    {QStringLiteral("🥵"), QStringLiteral("hot face")},
    {QStringLiteral("🥶"), QStringLiteral("cold face")},
    {QStringLiteral("🥴"), QStringLiteral("woozy face")},
    {QStringLiteral("😵"), QStringLiteral("face with crossed-out eyes")},
    {QStringLiteral("🤯"), QStringLiteral("exploding head")},
    {QStringLiteral("🤠"), QStringLiteral("cowboy hat face")},
    {QStringLiteral("🥳"), QStringLiteral("partying face")},
    {QStringLiteral("🥸"), QStringLiteral("disguised face")},
    {QStringLiteral("😎"), QStringLiteral("smiling face with sunglasses")},
    {QStringLiteral("🤓"), QStringLiteral("nerd face")},
    {QStringLiteral("🧐"), QStringLiteral("face with monocle")},
    {QStringLiteral("😕"), QStringLiteral("confused face")},
    {QStringLiteral("😟"), QStringLiteral("worried face")},
    {QStringLiteral("🙁"), QStringLiteral("slightly frowning face")},
    {QStringLiteral("☹️"), QStringLiteral("frowning face")},
    {QStringLiteral("😮"), QStringLiteral("face with open mouth")},
    {QStringLiteral("😯"), QStringLiteral("hushed face")},
    {QStringLiteral("😲"), QStringLiteral("astonished face")},
    {QStringLiteral("😳"), QStringLiteral("flushed face")},
    {QStringLiteral("🥺"), QStringLiteral("pleading face")},
    {QStringLiteral("😦"), QStringLiteral("frowning face with open mouth")},
    {QStringLiteral("😧"), QStringLiteral("anguished face")},
    {QStringLiteral("😨"), QStringLiteral("fearful face")},
    {QStringLiteral("😰"), QStringLiteral("anxious face with sweat")},
    {QStringLiteral("😥"), QStringLiteral("sad but relieved face")},
    {QStringLiteral("😢"), QStringLiteral("crying face")},
    {QStringLiteral("😭"), QStringLiteral("loudly crying face")},
    {QStringLiteral("😱"), QStringLiteral("face screaming in fear")},
    {QStringLiteral("😖"), QStringLiteral("confounded face")},
    {QStringLiteral("😣"), QStringLiteral("persevering face")},
    {QStringLiteral("😞"), QStringLiteral("disappointed face")},
    {QStringLiteral("😓"), QStringLiteral("downcast face with sweat")},
    {QStringLiteral("😩"), QStringLiteral("weary face")},
    {QStringLiteral("😫"), QStringLiteral("tired face")},
    {QStringLiteral("🥱"), QStringLiteral("yawning face")},
    {QStringLiteral("😤"), QStringLiteral("face with steam from nose")},
    {QStringLiteral("😡"), QStringLiteral("enraged face")},
    {QStringLiteral("😠"), QStringLiteral("angry face")},
    {QStringLiteral("🤬"), QStringLiteral("face with symbols on mouth")},
    {QStringLiteral("😈"), QStringLiteral("smiling face with horns")},
    {QStringLiteral("👿"), QStringLiteral("angry face with horns")},
    {QStringLiteral("💀"), QStringLiteral("skull")},
    {QStringLiteral("☠️"), QStringLiteral("skull and crossbones")},
    {QStringLiteral("💩"), QStringLiteral("pile of poo")},
    {QStringLiteral("🤡"), QStringLiteral("clown face")},
    {QStringLiteral("👹"), QStringLiteral("ogre")},
    {QStringLiteral("👺"), QStringLiteral("goblin")},
    {QStringLiteral("👻"), QStringLiteral("ghost")},
    {QStringLiteral("👽️"), QStringLiteral("alien")},
    {QStringLiteral("👾"), QStringLiteral("alien monster")},
    {QStringLiteral("🤖"), QStringLiteral("robot")},
    {QStringLiteral("😺"), QStringLiteral("grinning cat")},
    {QStringLiteral("😸"), QStringLiteral("grinning cat with smiling eyes")},
    {QStringLiteral("😹"), QStringLiteral("cat with tears of joy")},
    {QStringLiteral("😻"), QStringLiteral("smiling cat with heart-eyes")},
    {QStringLiteral("😼"), QStringLiteral("cat with wry smile")},
    {QStringLiteral("😽"), QStringLiteral("kissing cat")},
    {QStringLiteral("🙀"), QStringLiteral("weary cat")},
    {QStringLiteral("😿"), QStringLiteral("crying cat")},
    {QStringLiteral("😾"), QStringLiteral("pouting cat")},
    {QStringLiteral("🙈"), QStringLiteral("see-no-evil monkey")},
    {QStringLiteral("🙉"), QStringLiteral("hear-no-evil monkey")},
    {QStringLiteral("🙊"), QStringLiteral("speak-no-evil monkey")},
    {QStringLiteral("💋"), QStringLiteral("kiss mark")},
    {QStringLiteral("💌"), QStringLiteral("love letter")},
    {QStringLiteral("💘"), QStringLiteral("heart with arrow")},
    {QStringLiteral("💝"), QStringLiteral("heart with ribbon")},
    {QStringLiteral("💖"), QStringLiteral("sparkling heart")},
    {QStringLiteral("💗"), QStringLiteral("growing heart")},
    {QStringLiteral("💓"), QStringLiteral("beating heart")},
    {QStringLiteral("💞"), QStringLiteral("revolving hearts")},
    {QStringLiteral("💕"), QStringLiteral("two hearts")},
    {QStringLiteral("💟"), QStringLiteral("heart decoration")},
    {QStringLiteral("❣️"), QStringLiteral("heart exclamation")},
    {QStringLiteral("💔"), QStringLiteral("broken heart")},
    {QStringLiteral("❤️"), QStringLiteral("red heart")},
    {QStringLiteral("🧡"), QStringLiteral("orange heart")},
    {QStringLiteral("💛"), QStringLiteral("yellow heart")},
    {QStringLiteral("💚"), QStringLiteral("green heart")},
    {QStringLiteral("💙"), QStringLiteral("blue heart")},
    {QStringLiteral("💜"), QStringLiteral("purple heart")},
    {QStringLiteral("🤎"), QStringLiteral("brown heart")},
    {QStringLiteral("🖤"), QStringLiteral("black heart")},
    {QStringLiteral("🤍"), QStringLiteral("white heart")},
    {QStringLiteral("💯"), QStringLiteral("hundred points")},
    {QStringLiteral("💢"), QStringLiteral("anger symbol")},
    {QStringLiteral("💥"), QStringLiteral("collision")},
    {QStringLiteral("💫"), QStringLiteral("dizzy")},
    {QStringLiteral("💦"), QStringLiteral("sweat droplets")},
    {QStringLiteral("💨"), QStringLiteral("dashing away")},
    {QStringLiteral("🕳️"), QStringLiteral("hole")},
    {QStringLiteral("💣"), QStringLiteral("bomb")},
    {QStringLiteral("💬"), QStringLiteral("speech balloon")},
    {QStringLiteral("👁️‍🗨️"), QStringLiteral("eye in speech bubble")},
    {QStringLiteral("🗨️"), QStringLiteral("left speech bubble")},
    {QStringLiteral("🗯️"), QStringLiteral("right anger bubble")},
    {QStringLiteral("💭"), QStringLiteral("thought balloon")},
    {QStringLiteral("💤"), QStringLiteral("zzz")},
    {QStringLiteral("👋"), QStringLiteral("waving hand")},
    {QStringLiteral("🤚"), QStringLiteral("raised back of hand")},
    {QStringLiteral("🖐️"), QStringLiteral("hand with fingers splayed")},
    {QStringLiteral("✋"), QStringLiteral("raised hand")},
    {QStringLiteral("🖖"), QStringLiteral("vulcan salute")},
    {QStringLiteral("👌"), QStringLiteral("OK hand")},
    {QStringLiteral("🤌"), QStringLiteral("pinched fingers")},
    {QStringLiteral("🤏"), QStringLiteral("pinching hand")},
    {QStringLiteral("✌️"), QStringLiteral("victory hand")},
    {QStringLiteral("🤞"), QStringLiteral("crossed fingers")},
    {QStringLiteral("🤟"), QStringLiteral("love-you gesture")},
    {QStringLiteral("🤘"), QStringLiteral("sign of the horns")},
    {QStringLiteral("🤙"), QStringLiteral("call me hand")},
    {QStringLiteral("👈"), QStringLiteral("backhand index pointing left")},
    {QStringLiteral("👉"), QStringLiteral("backhand index pointing right")},
    {QStringLiteral("👆"), QStringLiteral("backhand index pointing up")},
    {QStringLiteral("🖕"), QStringLiteral("middle finger")},
    {QStringLiteral("👇"), QStringLiteral("backhand index pointing down")},
    {QStringLiteral("☝️"), QStringLiteral("index pointing up")},
    {QStringLiteral("👍"), QStringLiteral("thumbs up")},
    {QStringLiteral("👎"), QStringLiteral("thumbs down")},
    {QStringLiteral("✊"), QStringLiteral("raised fist")},
    {QStringLiteral("👊"), QStringLiteral("oncoming fist")},
    {QStringLiteral("🤛"), QStringLiteral("left-facing fist")},
    {QStringLiteral("🤜"), QStringLiteral("right-facing fist")},
    {QStringLiteral("👏"), QStringLiteral("clapping hands")},
    {QStringLiteral("🙌"), QStringLiteral("raising hands")},
    {QStringLiteral("👐"), QStringLiteral("open hands")},
    {QStringLiteral("🤲"), QStringLiteral("palms up together")},
    {QStringLiteral("🤝"), QStringLiteral("handshake")},
    {QStringLiteral("🙏"), QStringLiteral("folded hands")},
    {QStringLiteral("✍️"), QStringLiteral("writing hand")},
    {QStringLiteral("💅"), QStringLiteral("nail polish")},
    {QStringLiteral("🤳"), QStringLiteral("selfie")},
    {QStringLiteral("💪"), QStringLiteral("flexed biceps")},
    {QStringLiteral("🦾"), QStringLiteral("mechanical arm")},
    {QStringLiteral("🦿"), QStringLiteral("mechanical leg")},
    {QStringLiteral("🦵"), QStringLiteral("leg")},
    {QStringLiteral("🦶"), QStringLiteral("foot")},
    {QStringLiteral("👂"), QStringLiteral("ear")},
    {QStringLiteral("🦻"), QStringLiteral("ear with hearing aid")},
    {QStringLiteral("👃"), QStringLiteral("nose")},
    {QStringLiteral("🧠"), QStringLiteral("brain")},
    {QStringLiteral("🫀"), QStringLiteral("anatomical heart")},
    {QStringLiteral("🫁"), QStringLiteral("lungs")},
    {QStringLiteral("🦷"), QStringLiteral("tooth")},
    {QStringLiteral("🦴"), QStringLiteral("bone")},
    {QStringLiteral("👀"), QStringLiteral("eyes")},
    {QStringLiteral("👁️"), QStringLiteral("eye")},
    {QStringLiteral("👅"), QStringLiteral("tongue")},
    {QStringLiteral("👄"), QStringLiteral("mouth")},
    {QStringLiteral("👶"), QStringLiteral("baby")},
    {QStringLiteral("🧒"), QStringLiteral("child")},
    {QStringLiteral("👦"), QStringLiteral("boy")},
    {QStringLiteral("👧"), QStringLiteral("girl")},
    {QStringLiteral("🧑"), QStringLiteral("person")},
    {QStringLiteral("👱"), QStringLiteral("person blond hair")},
    {QStringLiteral("👨"), QStringLiteral("man")},
    {QStringLiteral("🧔"), QStringLiteral("person beard")},
    {QStringLiteral("👩"), QStringLiteral("woman")},
    {QStringLiteral("🧓"), QStringLiteral("older person")},
    {QStringLiteral("👴"), QStringLiteral("old man")},
    {QStringLiteral("👵"), QStringLiteral("old woman")},
    {QStringLiteral("🙍"), QStringLiteral("person frowning")},
    {QStringLiteral("🙎"), QStringLiteral("person pouting")},
    {QStringLiteral("🙅"), QStringLiteral("person gesturing NO")},
    {QStringLiteral("🙆"), QStringLiteral("person gesturing OK")},
    {QStringLiteral("💁"), QStringLiteral("person tipping hand")},
    {QStringLiteral("🙋"), QStringLiteral("person raising hand")},
    {QStringLiteral("🧏"), QStringLiteral("deaf person")},
    {QStringLiteral("🙇"), QStringLiteral("person bowing")},
    {QStringLiteral("🤦"), QStringLiteral("person facepalming")},
    {QStringLiteral("🤷"), QStringLiteral("person shrugging")},
    {QStringLiteral("🧑‍⚕️"), QStringLiteral("health worker")},
    {QStringLiteral("🧑‍🎓"), QStringLiteral("student")},
    {QStringLiteral("🧑‍🏫"), QStringLiteral("teacher")},
    {QStringLiteral("🧑‍⚖️"), QStringLiteral("judge")},
    {QStringLiteral("🧑‍🌾"), QStringLiteral("farmer")},
    {QStringLiteral("🧑‍🍳"), QStringLiteral("cook")},
    {QStringLiteral("🧑‍🔧"), QStringLiteral("mechanic")},
    {QStringLiteral("🧑‍🏭"), QStringLiteral("factory worker")},
    {QStringLiteral("🧑‍💼"), QStringLiteral("office worker")},
    {QStringLiteral("🧑‍🔬"), QStringLiteral("scientist")},
    {QStringLiteral("🧑‍💻"), QStringLiteral("technologist")},
    {QStringLiteral("🧑‍🎤"), QStringLiteral("singer")},
    {QStringLiteral("🧑‍🎨"), QStringLiteral("artist")},
    {QStringLiteral("🧑‍✈️"), QStringLiteral("pilot")},
    {QStringLiteral("🧑‍🚀"), QStringLiteral("astronaut")},
    {QStringLiteral("🧑‍🚒"), QStringLiteral("firefighter")},
    {QStringLiteral("👮"), QStringLiteral("police officer")},
    {QStringLiteral("🕵️"), QStringLiteral("detective")},
    {QStringLiteral("💂"), QStringLiteral("guard")},
    {QStringLiteral("🥷"), QStringLiteral("ninja")},
    {QStringLiteral("👷"), QStringLiteral("construction worker")},
    {QStringLiteral("🤴"), QStringLiteral("prince")},
    {QStringLiteral("👸"), QStringLiteral("princess")},
    {QStringLiteral("👳"), QStringLiteral("person wearing turban")},
    {QStringLiteral("👲"), QStringLiteral("person with skullcap")},
    {QStringLiteral("🤵"), QStringLiteral("person in tuxedo")},
    {QStringLiteral("👰"), QStringLiteral("person with veil")},
    {QStringLiteral("🤰"), QStringLiteral("pregnant woman")},
    {QStringLiteral("🤱"), QStringLiteral("breast-feeding")},
    {QStringLiteral("👩‍🍼"), QStringLiteral("woman feeding baby")},
    {QStringLiteral("👨‍🍼"), QStringLiteral("man feeding baby")},
    {QStringLiteral("🧑‍🍼"), QStringLiteral("person feeding baby")},
    {QStringLiteral("👼"), QStringLiteral("baby angel")},
    {QStringLiteral("🎅"), QStringLiteral("Santa Claus")},
    {QStringLiteral("🤶"), QStringLiteral("Mrs Claus")},
    {QStringLiteral("🧑‍🎄"), QStringLiteral("mx claus")},
    {QStringLiteral("🦸"), QStringLiteral("superhero")},
    {QStringLiteral("🦹"), QStringLiteral("supervillain")},
    {QStringLiteral("🧙"), QStringLiteral("mage")},
    {QStringLiteral("🧚"), QStringLiteral("fairy")},
    {QStringLiteral("🧛"), QStringLiteral("vampire")},
    {QStringLiteral("🧜"), QStringLiteral("merperson")},
    {QStringLiteral("🧝"), QStringLiteral("elf")},
    {QStringLiteral("🧞"), QStringLiteral("genie")},
    {QStringLiteral("🧟"), QStringLiteral("zombie")},
    {QStringLiteral("🧌"), QStringLiteral("troll")},
    {QStringLiteral("💆"), QStringLiteral("person getting massage")},
    {QStringLiteral("💇"), QStringLiteral("person getting haircut")},
    {QStringLiteral("🚶"), QStringLiteral("person walking")},
    {QStringLiteral("🧍"), QStringLiteral("person standing")},
    {QStringLiteral("🧎"), QStringLiteral("person kneeling")},
    {QStringLiteral("🏃"), QStringLiteral("person running")},
    {QStringLiteral("💃"), QStringLiteral("woman dancing")},
    {QStringLiteral("🕺"), QStringLiteral("man dancing")},
    {QStringLiteral("🕴️"), QStringLiteral("person in suit levitating")},
    {QStringLiteral("👯"), QStringLiteral("people with bunny ears")},
    {QStringLiteral("🧖"), QStringLiteral("person in steamy room")},
    {QStringLiteral("🧗"), QStringLiteral("person climbing")},
    {QStringLiteral("🤺"), QStringLiteral("person fencing")},
    {QStringLiteral("🏇"), QStringLiteral("horse racing")},
    {QStringLiteral("⛷️"), QStringLiteral("skier")},
    {QStringLiteral("🏂"), QStringLiteral("snowboarder")},
    {QStringLiteral("🏌️"), QStringLiteral("person golfing")},
    {QStringLiteral("🏄"), QStringLiteral("person surfing")},
    {QStringLiteral("🚣"), QStringLiteral("person rowing boat")},
    {QStringLiteral("🏊"), QStringLiteral("person swimming")},
    {QStringLiteral("⛹️"), QStringLiteral("person bouncing ball")},
    {QStringLiteral("🏋️"), QStringLiteral("person lifting weights")},
    {QStringLiteral("🚴"), QStringLiteral("person biking")},
    {QStringLiteral("🚵"), QStringLiteral("person mountain biking")},
    {QStringLiteral("🤸"), QStringLiteral("person cartwheeling")},
    {QStringLiteral("🤼"), QStringLiteral("people wrestling")},
    {QStringLiteral("🤽"), QStringLiteral("person playing water polo")},
    {QStringLiteral("🤾"), QStringLiteral("person playing handball")},
    {QStringLiteral("🤹"), QStringLiteral("person juggling")},
    {QStringLiteral("🧘"), QStringLiteral("person in lotus position")},
    {QStringLiteral("🛀"), QStringLiteral("person taking bath")},
    {QStringLiteral("🛌"), QStringLiteral("person in bed")},
    {QStringLiteral("👭"), QStringLiteral("women holding hands")},
    {QStringLiteral("👫"), QStringLiteral("woman and man holding hands")},
    {QStringLiteral("👬"), QStringLiteral("men holding hands")},
    {QStringLiteral("💏"), QStringLiteral("kiss")},
    {QStringLiteral("💑"), QStringLiteral("couple with heart")},
    {QStringLiteral("👪"), QStringLiteral("family")},
    {QStringLiteral("🗣️"), QStringLiteral("speaking head")},
    {QStringLiteral("👤"), QStringLiteral("bust in silhouette")},
    {QStringLiteral("👥"), QStringLiteral("busts in silhouette")},
    {QStringLiteral("🫂"), QStringLiteral("people hugging")},
    {QStringLiteral("👣"), QStringLiteral("footprints")},
    {QStringLiteral("🦰"), QStringLiteral("red hair")},
    {QStringLiteral("🦱"), QStringLiteral("curly hair")},
    {QStringLiteral("🦳"), QStringLiteral("white hair")},
    {QStringLiteral("🦲"), QStringLiteral("bald")},
    {QStringLiteral("🐵"), QStringLiteral("monkey face")},
    {QStringLiteral("🐒"), QStringLiteral("monkey")},
    {QStringLiteral("🦍"), QStringLiteral("gorilla")},
    {QStringLiteral("🦧"), QStringLiteral("orangutan")},
    {QStringLiteral("🐶"), QStringLiteral("dog face")},
    {QStringLiteral("🐕"), QStringLiteral("dog")},
    {QStringLiteral("🦮"), QStringLiteral("guide dog")},
    {QStringLiteral("🐕‍🦺"), QStringLiteral("service dog")},
    {QStringLiteral("🐩"), QStringLiteral("poodle")},
    {QStringLiteral("🐺"), QStringLiteral("wolf")},
    {QStringLiteral("🦊"), QStringLiteral("fox")},
    {QStringLiteral("🦝"), QStringLiteral("raccoon")},
    {QStringLiteral("🐱"), QStringLiteral("cat face")},
    {QStringLiteral("🐈"), QStringLiteral("cat")},
    {QStringLiteral("🐈‍⬛"), QStringLiteral("black cat")},
    {QStringLiteral("🦁"), QStringLiteral("lion")},
    {QStringLiteral("🐯"), QStringLiteral("tiger face")},
    {QStringLiteral("🐅"), QStringLiteral("tiger")},
    {QStringLiteral("🐆"), QStringLiteral("leopard")},
    {QStringLiteral("🐴"), QStringLiteral("horse face")},
    {QStringLiteral("🐎"), QStringLiteral("horse")},
    {QStringLiteral("🦄"), QStringLiteral("unicorn")},
    {QStringLiteral("🦓"), QStringLiteral("zebra")},
    {QStringLiteral("🦌"), QStringLiteral("deer")},
    {QStringLiteral("🦬"), QStringLiteral("bison")},
    {QStringLiteral("🐮"), QStringLiteral("cow face")},
    {QStringLiteral("🐂"), QStringLiteral("ox")},
    {QStringLiteral("🐃"), QStringLiteral("water buffalo")},
    {QStringLiteral("🐄"), QStringLiteral("cow")},
    {QStringLiteral("🐷"), QStringLiteral("pig face")},
    {QStringLiteral("🐖"), QStringLiteral("pig")},
    {QStringLiteral("🐗"), QStringLiteral("boar")},
    {QStringLiteral("🐽"), QStringLiteral("pig nose")},
    {QStringLiteral("🐏"), QStringLiteral("ram")},
    {QStringLiteral("🐑"), QStringLiteral("ewe")},
    {QStringLiteral("🐐"), QStringLiteral("goat")},
    {QStringLiteral("🐪"), QStringLiteral("camel")},
    {QStringLiteral("🐫"), QStringLiteral("two-hump camel")},
    {QStringLiteral("🦙"), QStringLiteral("llama")},
    {QStringLiteral("🦒"), QStringLiteral("giraffe")},
    {QStringLiteral("🐘"), QStringLiteral("elephant")},
    {QStringLiteral("🦣"), QStringLiteral("mammoth")},
    {QStringLiteral("🦏"), QStringLiteral("rhinoceros")},
    {QStringLiteral("🦛"), QStringLiteral("hippopotamus")},
    {QStringLiteral("🐭"), QStringLiteral("mouse face")},
    {QStringLiteral("🐁"), QStringLiteral("mouse")},
    {QStringLiteral("🐀"), QStringLiteral("rat")},
    {QStringLiteral("🐹"), QStringLiteral("hamster")},
    {QStringLiteral("🐰"), QStringLiteral("rabbit face")},
    {QStringLiteral("🐇"), QStringLiteral("rabbit")},
    {QStringLiteral("🐿️"), QStringLiteral("chipmunk")},
    {QStringLiteral("🦫"), QStringLiteral("beaver")},
    {QStringLiteral("🦔"), QStringLiteral("hedgehog")},
    {QStringLiteral("🦇"), QStringLiteral("bat")},
    {QStringLiteral("🐻"), QStringLiteral("bear")},
    {QStringLiteral("🐻‍❄️"), QStringLiteral("polar bear")},
    {QStringLiteral("🐨"), QStringLiteral("koala")},
    {QStringLiteral("🐼"), QStringLiteral("panda")},
    {QStringLiteral("🦥"), QStringLiteral("sloth")},
    {QStringLiteral("🦦"), QStringLiteral("otter")},
    {QStringLiteral("🦨"), QStringLiteral("skunk")},
    {QStringLiteral("🦘"), QStringLiteral("kangaroo")},
    {QStringLiteral("🦡"), QStringLiteral("badger")},
    {QStringLiteral("🐾"), QStringLiteral("paw prints")},
    {QStringLiteral("🦃"), QStringLiteral("turkey")},
    {QStringLiteral("🐔"), QStringLiteral("chicken")},
    {QStringLiteral("🐓"), QStringLiteral("rooster")},
    {QStringLiteral("🐣"), QStringLiteral("hatching chick")},
    {QStringLiteral("🐤"), QStringLiteral("baby chick")},
    {QStringLiteral("🐥"), QStringLiteral("front-facing baby chick")},
    {QStringLiteral("🐦"), QStringLiteral("bird")},
    {QStringLiteral("🐧"), QStringLiteral("penguin")},
    {QStringLiteral("🕊️"), QStringLiteral("dove")},
    {QStringLiteral("🦅"), QStringLiteral("eagle")},
    {QStringLiteral("🦆"), QStringLiteral("duck")},
    {QStringLiteral("🦢"), QStringLiteral("swan")},
    {QStringLiteral("🦉"), QStringLiteral("owl")},
    {QStringLiteral("🦤"), QStringLiteral("dodo")},
    {QStringLiteral("🪶"), QStringLiteral("feather")},
    {QStringLiteral("🦩"), QStringLiteral("flamingo")},
    {QStringLiteral("🦚"), QStringLiteral("peacock")},
    {QStringLiteral("🦜"), QStringLiteral("parrot")},
    {QStringLiteral("🐸"), QStringLiteral("frog")},
    {QStringLiteral("🐊"), QStringLiteral("crocodile")},
    {QStringLiteral("🐢"), QStringLiteral("turtle")},
    {QStringLiteral("🦎"), QStringLiteral("lizard")},
    {QStringLiteral("🐍"), QStringLiteral("snake")},
    {QStringLiteral("🐲"), QStringLiteral("dragon face")},
    {QStringLiteral("🐉"), QStringLiteral("dragon")},
    {QStringLiteral("🦕"), QStringLiteral("sauropod")},
    {QStringLiteral("🦖"), QStringLiteral("T-Rex")},
    {QStringLiteral("🐳"), QStringLiteral("spouting whale")},
    {QStringLiteral("🐋"), QStringLiteral("whale")},
    {QStringLiteral("🐬"), QStringLiteral("dolphin")},
    {QStringLiteral("🦭"), QStringLiteral("seal")},
    {QStringLiteral("🐟"), QStringLiteral("fish")},
    {QStringLiteral("🐠"), QStringLiteral("tropical fish")},
    {QStringLiteral("🐡"), QStringLiteral("blowfish")},
    {QStringLiteral("🦈"), QStringLiteral("shark")},
    {QStringLiteral("🐙"), QStringLiteral("octopus")},
    {QStringLiteral("🐚"), QStringLiteral("spiral shell")},
    {QStringLiteral("🪸"), QStringLiteral("coral")},
    {QStringLiteral("🐌"), QStringLiteral("snail")},
    {QStringLiteral("🦋"), QStringLiteral("butterfly")},
    {QStringLiteral("🐛"), QStringLiteral("bug")},
    {QStringLiteral("🐜"), QStringLiteral("ant")},
    {QStringLiteral("🐝"), QStringLiteral("honeybee")},
    {QStringLiteral("🪲"), QStringLiteral("beetle")},
    {QStringLiteral("🐞"), QStringLiteral("lady beetle")},
    {QStringLiteral("🦗"), QStringLiteral("cricket")},
    {QStringLiteral("🪳"), QStringLiteral("cockroach")},
    {QStringLiteral("🕷️"), QStringLiteral("spider")},
    {QStringLiteral("🕸️"), QStringLiteral("spider web")},
    {QStringLiteral("🦂"), QStringLiteral("scorpion")},
    {QStringLiteral("🦟"), QStringLiteral("mosquito")},
    {QStringLiteral("🪰"), QStringLiteral("fly")},
    {QStringLiteral("🪱"), QStringLiteral("worm")},
    {QStringLiteral("🦠"), QStringLiteral("microbe")},
    {QStringLiteral("💐"), QStringLiteral("bouquet")},
    {QStringLiteral("🌸"), QStringLiteral("cherry blossom")},
    {QStringLiteral("💮"), QStringLiteral("white flower")},
    {QStringLiteral("🪷"), QStringLiteral("lotus")},
    {QStringLiteral("🏵️"), QStringLiteral("rosette")},
    {QStringLiteral("🌹"), QStringLiteral("rose")},
    {QStringLiteral("🥀"), QStringLiteral("wilted flower")},
    {QStringLiteral("🌺"), QStringLiteral("hibiscus")},
    {QStringLiteral("🌻"), QStringLiteral("sunflower")},
    {QStringLiteral("🌼"), QStringLiteral("blossom")},
    {QStringLiteral("🌷"), QStringLiteral("tulip")},
    {QStringLiteral("🌱"), QStringLiteral("seedling")},
    {QStringLiteral("🪴"), QStringLiteral("potted plant")},
    {QStringLiteral("🌲"), QStringLiteral("evergreen tree")},
    {QStringLiteral("🌳"), QStringLiteral("deciduous tree")},
    {QStringLiteral("🌴"), QStringLiteral("palm tree")},
    {QStringLiteral("🌵"), QStringLiteral("cactus")},
    {QStringLiteral("🌾"), QStringLiteral("sheaf of rice")},
    {QStringLiteral("🌿"), QStringLiteral("herb")},
    {QStringLiteral("☘️"), QStringLiteral("shamrock")},
    {QStringLiteral("🍀"), QStringLiteral("four leaf clover")},
    {QStringLiteral("🍁"), QStringLiteral("maple leaf")},
    {QStringLiteral("🍂"), QStringLiteral("fallen leaf")},
    {QStringLiteral("🍃"), QStringLiteral("leaf fluttering in wind")},
    {QStringLiteral("🍇"), QStringLiteral("grapes")},
    {QStringLiteral("🍈"), QStringLiteral("melon")},
    {QStringLiteral("🍉"), QStringLiteral("watermelon")},
    {QStringLiteral("🍊"), QStringLiteral("tangerine")},
    {QStringLiteral("🍋"), QStringLiteral("lemon")},
    {QStringLiteral("🍌"), QStringLiteral("banana")},
    {QStringLiteral("🍍"), QStringLiteral("pineapple")},
    {QStringLiteral("🍎"), QStringLiteral("red apple")},
    {QStringLiteral("🍏"), QStringLiteral("green apple")},
    {QStringLiteral("🍐"), QStringLiteral("pear")},
    {QStringLiteral("🍑"), QStringLiteral("peach")},
    {QStringLiteral("🍒"), QStringLiteral("cherries")},
    {QStringLiteral("🍓"), QStringLiteral("strawberry")},
    {QStringLiteral("🫐"), QStringLiteral("blueberries")},
    {QStringLiteral("🥝"), QStringLiteral("kiwi fruit")},
    {QStringLiteral("🍅"), QStringLiteral("tomato")},
    {QStringLiteral("🫒"), QStringLiteral("olive")},
    {QStringLiteral("🥥"), QStringLiteral("coconut")},
    {QStringLiteral("🥑"), QStringLiteral("avocado")},
    {QStringLiteral("🍆"), QStringLiteral("eggplant")},
    {QStringLiteral("🥔"), QStringLiteral("potato")},
    {QStringLiteral("🥕"), QStringLiteral("carrot")},
    {QStringLiteral("🌽"), QStringLiteral("ear of corn")},
    {QStringLiteral("🌶️"), QStringLiteral("hot pepper")},
    {QStringLiteral("🫑"), QStringLiteral("bell pepper")},
    {QStringLiteral("🥒"), QStringLiteral("cucumber")},
    {QStringLiteral("🥬"), QStringLiteral("leafy green")},
    {QStringLiteral("🥦"), QStringLiteral("broccoli")},
    {QStringLiteral("🧄"), QStringLiteral("garlic")},
    {QStringLiteral("🧅"), QStringLiteral("onion")},
    {QStringLiteral("🍄"), QStringLiteral("mushroom")},
    {QStringLiteral("🥜"), QStringLiteral("peanuts")},
    {QStringLiteral("🫘"), QStringLiteral("beans")},
    {QStringLiteral("🌰"), QStringLiteral("chestnut")},
    {QStringLiteral("🍞"), QStringLiteral("bread")},
    {QStringLiteral("🥐"), QStringLiteral("croissant")},
    {QStringLiteral("🥖"), QStringLiteral("baguette bread")},
    {QStringLiteral("🫓"), QStringLiteral("flatbread")},
    {QStringLiteral("🥨"), QStringLiteral("pretzel")},
    {QStringLiteral("🥯"), QStringLiteral("bagel")},
    {QStringLiteral("🥞"), QStringLiteral("pancakes")},
    {QStringLiteral("🧇"), QStringLiteral("waffle")},
    {QStringLiteral("🧀"), QStringLiteral("cheese wedge")},
    {QStringLiteral("🍖"), QStringLiteral("meat on bone")},
    {QStringLiteral("🍗"), QStringLiteral("poultry leg")},
    {QStringLiteral("🥩"), QStringLiteral("cut of meat")},
    {QStringLiteral("🥓"), QStringLiteral("bacon")},
    {QStringLiteral("🍔"), QStringLiteral("hamburger")},
    {QStringLiteral("🍟"), QStringLiteral("french fries")},
    {QStringLiteral("🍕"), QStringLiteral("pizza")},
    {QStringLiteral("🌭"), QStringLiteral("hot dog")},
    {QStringLiteral("🥪"), QStringLiteral("sandwich")},
    {QStringLiteral("🌮"), QStringLiteral("taco")},
    {QStringLiteral("🌯"), QStringLiteral("burrito")},
    {QStringLiteral("🫔"), QStringLiteral("tamale")},
    {QStringLiteral("🥙"), QStringLiteral("stuffed flatbread")},
    {QStringLiteral("🧆"), QStringLiteral("falafel")},
    {QStringLiteral("🥚"), QStringLiteral("egg")},
    {QStringLiteral("🍳"), QStringLiteral("cooking")},
    {QStringLiteral("🥘"), QStringLiteral("shallow pan of food")},
    {QStringLiteral("🍲"), QStringLiteral("pot of food")},
    {QStringLiteral("🫕"), QStringLiteral("fondue")},
    {QStringLiteral("🥣"), QStringLiteral("bowl with spoon")},
    {QStringLiteral("🥗"), QStringLiteral("green salad")},
    {QStringLiteral("🍿"), QStringLiteral("popcorn")},
    {QStringLiteral("🧈"), QStringLiteral("butter")},
    {QStringLiteral("🧂"), QStringLiteral("salt")},
    {QStringLiteral("🥫"), QStringLiteral("canned food")},
    {QStringLiteral("🍱"), QStringLiteral("bento box")},
    {QStringLiteral("🍘"), QStringLiteral("rice cracker")},
    {QStringLiteral("🍙"), QStringLiteral("rice ball")},
    {QStringLiteral("🍚"), QStringLiteral("cooked rice")},
    {QStringLiteral("🍛"), QStringLiteral("curry rice")},
    {QStringLiteral("🍜"), QStringLiteral("steaming bowl")},
    {QStringLiteral("🍝"), QStringLiteral("spaghetti")},
    {QStringLiteral("🍠"), QStringLiteral("roasted sweet potato")},
    {QStringLiteral("🍢"), QStringLiteral("oden")},
    {QStringLiteral("🍣"), QStringLiteral("sushi")},
    {QStringLiteral("🍤"), QStringLiteral("fried shrimp")},
    {QStringLiteral("🍥"), QStringLiteral("fish cake with swirl")},
    {QStringLiteral("🥮"), QStringLiteral("moon cake")},
    {QStringLiteral("🍡"), QStringLiteral("dango")},
    {QStringLiteral("🥟"), QStringLiteral("dumpling")},
    {QStringLiteral("🥠"), QStringLiteral("fortune cookie")},
    {QStringLiteral("🥡"), QStringLiteral("takeout box")},
    {QStringLiteral("🦀"), QStringLiteral("crab")},
    {QStringLiteral("🦞"), QStringLiteral("lobster")},
    {QStringLiteral("🦐"), QStringLiteral("shrimp")},
    {QStringLiteral("🦑"), QStringLiteral("squid")},
    {QStringLiteral("🦪"), QStringLiteral("oyster")},
    {QStringLiteral("🍦"), QStringLiteral("soft ice cream")},
    {QStringLiteral("🍧"), QStringLiteral("shaved ice")},
    {QStringLiteral("🍨"), QStringLiteral("ice cream")},
    {QStringLiteral("🍩"), QStringLiteral("doughnut")},
    {QStringLiteral("🍪"), QStringLiteral("cookie")},
    {QStringLiteral("🎂"), QStringLiteral("birthday cake")},
    {QStringLiteral("🍰"), QStringLiteral("shortcake")},
    {QStringLiteral("🧁"), QStringLiteral("cupcake")},
    {QStringLiteral("🥧"), QStringLiteral("pie")},
    {QStringLiteral("🍫"), QStringLiteral("chocolate bar")},
    {QStringLiteral("🍬"), QStringLiteral("candy")},
    {QStringLiteral("🍭"), QStringLiteral("lollipop")},
    {QStringLiteral("🍮"), QStringLiteral("custard")},
    {QStringLiteral("🍯"), QStringLiteral("honey pot")},
    {QStringLiteral("🍼"), QStringLiteral("baby bottle")},
    {QStringLiteral("🥛"), QStringLiteral("glass of milk")},
    {QStringLiteral("☕"), QStringLiteral("hot beverage")},
    {QStringLiteral("🫖"), QStringLiteral("teapot")},
    {QStringLiteral("🍵"), QStringLiteral("teacup without handle")},
    {QStringLiteral("🍶"), QStringLiteral("sake")},
    {QStringLiteral("🍾"), QStringLiteral("bottle with popping cork")},
    {QStringLiteral("🍷"), QStringLiteral("wine glass")},
    {QStringLiteral("🍸"), QStringLiteral("cocktail glass")},
    {QStringLiteral("🍹"), QStringLiteral("tropical drink")},
    {QStringLiteral("🍺"), QStringLiteral("beer mug")},
    {QStringLiteral("🍻"), QStringLiteral("clinking beer mugs")},
    {QStringLiteral("🥂"), QStringLiteral("clinking glasses")},
    {QStringLiteral("🥃"), QStringLiteral("tumbler glass")},
    {QStringLiteral("🫗"), QStringLiteral("pouring liquid")},
    {QStringLiteral("🥤"), QStringLiteral("cup with straw")},
    {QStringLiteral("🧋"), QStringLiteral("bubble tea")},
    {QStringLiteral("🧃"), QStringLiteral("beverage box")},
    {QStringLiteral("🧉"), QStringLiteral("mate")},
    {QStringLiteral("🧊"), QStringLiteral("ice")},
    {QStringLiteral("🥢"), QStringLiteral("chopsticks")},
    {QStringLiteral("🍽️"), QStringLiteral("fork and knife with plate")},
    {QStringLiteral("🍴"), QStringLiteral("fork and knife")},
    {QStringLiteral("🥄"), QStringLiteral("spoon")},
    {QStringLiteral("🔪"), QStringLiteral("kitchen knife")},
    {QStringLiteral("🫙"), QStringLiteral("jar")},
    {QStringLiteral("🏺"), QStringLiteral("amphora")},
    {QStringLiteral("🌍"), QStringLiteral("globe showing Europe-Africa")},
    {QStringLiteral("🌎"), QStringLiteral("globe showing Americas")},
    {QStringLiteral("🌏"), QStringLiteral("globe showing Asia-Australia")},
    {QStringLiteral("🌐"), QStringLiteral("globe with meridians")},
    {QStringLiteral("🗺️"), QStringLiteral("world map")},
    {QStringLiteral("🗾"), QStringLiteral("map of Japan")},
    {QStringLiteral("🧭"), QStringLiteral("compass")},
    {QStringLiteral("🏔️"), QStringLiteral("snow-capped mountain")},
    {QStringLiteral("⛰️"), QStringLiteral("mountain")},
    {QStringLiteral("🌋"), QStringLiteral("volcano")},
    {QStringLiteral("🗻"), QStringLiteral("mount fuji")},
    {QStringLiteral("🏕️"), QStringLiteral("camping")},
    {QStringLiteral("🏖️"), QStringLiteral("beach with umbrella")},
    {QStringLiteral("🏜️"), QStringLiteral("desert")},
    {QStringLiteral("🏝️"), QStringLiteral("desert island")},
    {QStringLiteral("🏞️"), QStringLiteral("national park")},
    {QStringLiteral("🏟️"), QStringLiteral("stadium")},
    {QStringLiteral("🏛️"), QStringLiteral("classical building")},
    {QStringLiteral("🏗️"), QStringLiteral("building construction")},
    {QStringLiteral("🧱"), QStringLiteral("brick")},
    {QStringLiteral("🪨"), QStringLiteral("rock")},
    {QStringLiteral("🪵"), QStringLiteral("wood")},
    {QStringLiteral("🛖"), QStringLiteral("hut")},
    {QStringLiteral("🏘️"), QStringLiteral("houses")},
    {QStringLiteral("🏚️"), QStringLiteral("derelict house")},
    {QStringLiteral("🏠"), QStringLiteral("house")},
    {QStringLiteral("🏡"), QStringLiteral("house with garden")},
    {QStringLiteral("🏢"), QStringLiteral("office building")},
    {QStringLiteral("🏣"), QStringLiteral("Japanese post office")},
    {QStringLiteral("🏤"), QStringLiteral("post office")},
    {QStringLiteral("🏥"), QStringLiteral("hospital")},
    {QStringLiteral("🏦"), QStringLiteral("bank")},
    {QStringLiteral("🏨"), QStringLiteral("hotel")},
    {QStringLiteral("🏩"), QStringLiteral("love hotel")},
    {QStringLiteral("🏪"), QStringLiteral("convenience store")},
    {QStringLiteral("🏫"), QStringLiteral("school")},
    {QStringLiteral("🏬"), QStringLiteral("department store")},
    {QStringLiteral("🏭"), QStringLiteral("factory")},
    {QStringLiteral("🏯"), QStringLiteral("Japanese castle")},
    {QStringLiteral("🏰"), QStringLiteral("castle")},
    {QStringLiteral("💒"), QStringLiteral("wedding")},
    {QStringLiteral("🗼"), QStringLiteral("Tokyo tower")},
    {QStringLiteral("🗽"), QStringLiteral("Statue of Liberty")},
    {QStringLiteral("⛪"), QStringLiteral("church")},
    {QStringLiteral("🕌"), QStringLiteral("mosque")},
    {QStringLiteral("🛕"), QStringLiteral("hindu temple")},
    {QStringLiteral("🕍"), QStringLiteral("synagogue")},
    {QStringLiteral("⛩️"), QStringLiteral("shinto shrine")},
    {QStringLiteral("🕋"), QStringLiteral("kaaba")},
    {QStringLiteral("⛲"), QStringLiteral("fountain")},
    {QStringLiteral("⛺"), QStringLiteral("tent")},
    {QStringLiteral("🌁"), QStringLiteral("foggy")},
    {QStringLiteral("🌃"), QStringLiteral("night with stars")},
    {QStringLiteral("🏙️"), QStringLiteral("cityscape")},
    {QStringLiteral("🌄"), QStringLiteral("sunrise over mountains")},
    {QStringLiteral("🌅"), QStringLiteral("sunrise")},
    {QStringLiteral("🌆"), QStringLiteral("cityscape at dusk")},
    {QStringLiteral("🌇"), QStringLiteral("sunset")},
    {QStringLiteral("🌉"), QStringLiteral("bridge at night")},
    {QStringLiteral("♨️"), QStringLiteral("hot springs")},
    {QStringLiteral("🎠"), QStringLiteral("carousel horse")},
    {QStringLiteral("🛝"), QStringLiteral("playground slide")},
    {QStringLiteral("🎡"), QStringLiteral("ferris wheel")},
    {QStringLiteral("🎢"), QStringLiteral("roller coaster")},
    {QStringLiteral("💈"), QStringLiteral("barber pole")},
    {QStringLiteral("🎪"), QStringLiteral("circus tent")},
    {QStringLiteral("🚂"), QStringLiteral("locomotive")},
    {QStringLiteral("🚃"), QStringLiteral("railway car")},
    {QStringLiteral("🚄"), QStringLiteral("high-speed train")},
    {QStringLiteral("🚅"), QStringLiteral("bullet train")},
    {QStringLiteral("🚆"), QStringLiteral("train")},
    {QStringLiteral("🚇"), QStringLiteral("metro")},
    {QStringLiteral("🚈"), QStringLiteral("light rail")},
    {QStringLiteral("🚉"), QStringLiteral("station")},
    {QStringLiteral("🚊"), QStringLiteral("tram")},
    {QStringLiteral("🚝"), QStringLiteral("monorail")},
    {QStringLiteral("🚞"), QStringLiteral("mountain railway")},
    {QStringLiteral("🚋"), QStringLiteral("tram car")},
    {QStringLiteral("🚌"), QStringLiteral("bus")},
    {QStringLiteral("🚍"), QStringLiteral("oncoming bus")},
    {QStringLiteral("🚎"), QStringLiteral("trolleybus")},
    {QStringLiteral("🚐"), QStringLiteral("minibus")},
    {QStringLiteral("🚑"), QStringLiteral("ambulance")},
    {QStringLiteral("🚒"), QStringLiteral("fire engine")},
    {QStringLiteral("🚓"), QStringLiteral("police car")},
    {QStringLiteral("🚔"), QStringLiteral("oncoming police car")},
    {QStringLiteral("🚕"), QStringLiteral("taxi")},
    {QStringLiteral("🚖"), QStringLiteral("oncoming taxi")},
    {QStringLiteral("🚗"), QStringLiteral("automobile")},
    {QStringLiteral("🚘"), QStringLiteral("oncoming automobile")},
    {QStringLiteral("🚙"), QStringLiteral("sport utility vehicle")},
    {QStringLiteral("🛻"), QStringLiteral("pickup truck")},
    {QStringLiteral("🚚"), QStringLiteral("delivery truck")},
    {QStringLiteral("🚛"), QStringLiteral("articulated lorry")},
    {QStringLiteral("🚜"), QStringLiteral("tractor")},
    {QStringLiteral("🏎️"), QStringLiteral("racing car")},
    {QStringLiteral("🏍️"), QStringLiteral("motorcycle")},
    {QStringLiteral("🛵"), QStringLiteral("motor scooter")},
    {QStringLiteral("🦽"), QStringLiteral("manual wheelchair")},
    {QStringLiteral("🦼"), QStringLiteral("motorized wheelchair")},
    {QStringLiteral("🛺"), QStringLiteral("auto rickshaw")},
    {QStringLiteral("🚲"), QStringLiteral("bicycle")},
    {QStringLiteral("🛴"), QStringLiteral("kick scooter")},
    {QStringLiteral("🛹"), QStringLiteral("skateboard")},
    {QStringLiteral("🛼"), QStringLiteral("roller skate")},
    {QStringLiteral("🚏"), QStringLiteral("bus stop")},
    {QStringLiteral("🛣️"), QStringLiteral("motorway")},
    {QStringLiteral("🛤️"), QStringLiteral("railway track")},
    {QStringLiteral("🛢️"), QStringLiteral("oil drum")},
    {QStringLiteral("⛽"), QStringLiteral("fuel pump")},
    {QStringLiteral("🛞"), QStringLiteral("wheel")},
    {QStringLiteral("🚨"), QStringLiteral("police car light")},
    {QStringLiteral("🚥"), QStringLiteral("horizontal traffic light")},
    {QStringLiteral("🚦"), QStringLiteral("vertical traffic light")},
    {QStringLiteral("🛑"), QStringLiteral("stop sign")},
    {QStringLiteral("🚧"), QStringLiteral("construction")},
    {QStringLiteral("⚓"), QStringLiteral("anchor")},
    {QStringLiteral("🛟"), QStringLiteral("ring buoy")},
    {QStringLiteral("⛵"), QStringLiteral("sailboat")},
    {QStringLiteral("🛶"), QStringLiteral("canoe")},
    {QStringLiteral("🚤"), QStringLiteral("speedboat")},
    {QStringLiteral("🛳️"), QStringLiteral("passenger ship")},
    {QStringLiteral("⛴️"), QStringLiteral("ferry")},
    {QStringLiteral("🛥️"), QStringLiteral("motor boat")},
    {QStringLiteral("🚢"), QStringLiteral("ship")},
    {QStringLiteral("✈️"), QStringLiteral("airplane")},
    {QStringLiteral("🛩️"), QStringLiteral("small airplane")},
    {QStringLiteral("🛫"), QStringLiteral("airplane departure")},
    {QStringLiteral("🛬"), QStringLiteral("airplane arrival")},
    {QStringLiteral("🪂"), QStringLiteral("parachute")},
    {QStringLiteral("💺"), QStringLiteral("seat")},
    {QStringLiteral("🚁"), QStringLiteral("helicopter")},
    {QStringLiteral("🚟"), QStringLiteral("suspension railway")},
    {QStringLiteral("🚠"), QStringLiteral("mountain cableway")},
    {QStringLiteral("🚡"), QStringLiteral("aerial tramway")},
    {QStringLiteral("🛰️"), QStringLiteral("satellite")},
    {QStringLiteral("🚀"), QStringLiteral("rocket")},
    {QStringLiteral("🛸"), QStringLiteral("flying saucer")},
    {QStringLiteral("🛎️"), QStringLiteral("bellhop bell")},
    {QStringLiteral("🧳"), QStringLiteral("luggage")},
    {QStringLiteral("⌛"), QStringLiteral("hourglass done")},
    {QStringLiteral("⏳"), QStringLiteral("hourglass not done")},
    {QStringLiteral("⌚"), QStringLiteral("watch")},
    {QStringLiteral("⏰"), QStringLiteral("alarm clock")},
    {QStringLiteral("⏱️"), QStringLiteral("stopwatch")},
    {QStringLiteral("⏲️"), QStringLiteral("timer clock")},
    {QStringLiteral("🕰️"), QStringLiteral("mantelpiece clock")},
    {QStringLiteral("🕛"), QStringLiteral("twelve oclock")},
    {QStringLiteral("🌑"), QStringLiteral("new moon")},
    {QStringLiteral("🌒"), QStringLiteral("waxing crescent moon")},
    {QStringLiteral("🌓"), QStringLiteral("first quarter moon")},
    {QStringLiteral("🌔"), QStringLiteral("waxing gibbous moon")},
    {QStringLiteral("🌕"), QStringLiteral("full moon")},
    {QStringLiteral("🌖"), QStringLiteral("waning gibbous moon")},
    {QStringLiteral("🌗"), QStringLiteral("last quarter moon")},
    {QStringLiteral("🌘"), QStringLiteral("waning crescent moon")},
    {QStringLiteral("🌙"), QStringLiteral("crescent moon")},
    {QStringLiteral("🌚"), QStringLiteral("new moon face")},
    {QStringLiteral("🌛"), QStringLiteral("first quarter moon face")},
    {QStringLiteral("🌜"), QStringLiteral("last quarter moon face")},
    {QStringLiteral("🌡️"), QStringLiteral("thermometer")},
    {QStringLiteral("☀️"), QStringLiteral("sun")},
    {QStringLiteral("🌝"), QStringLiteral("full moon face")},
    {QStringLiteral("🌞"), QStringLiteral("sun with face")},
    {QStringLiteral("🪐"), QStringLiteral("ringed planet")},
    {QStringLiteral("⭐"), QStringLiteral("star")},
    {QStringLiteral("🌟"), QStringLiteral("glowing star")},
    {QStringLiteral("🌠"), QStringLiteral("shooting star")},
    {QStringLiteral("🌌"), QStringLiteral("milky way")},
    {QStringLiteral("☁️"), QStringLiteral("cloud")},
    {QStringLiteral("⛅"), QStringLiteral("sun behind cloud")},
    {QStringLiteral("⛈️"), QStringLiteral("cloud with lightning and rain")},
    {QStringLiteral("🌤️"), QStringLiteral("sun behind small cloud")},
    {QStringLiteral("🌥️"), QStringLiteral("sun behind large cloud")},
    {QStringLiteral("🌦️"), QStringLiteral("sun behind rain cloud")},
    {QStringLiteral("🌧️"), QStringLiteral("cloud with rain")},
    {QStringLiteral("🌨️"), QStringLiteral("cloud with snow")},
    {QStringLiteral("🌩️"), QStringLiteral("cloud with lightning")},
    {QStringLiteral("🌪️"), QStringLiteral("tornado")},
    {QStringLiteral("🌫️"), QStringLiteral("fog")},
    {QStringLiteral("🌬️"), QStringLiteral("wind face")},
    {QStringLiteral("🌀"), QStringLiteral("cyclone")},
    {QStringLiteral("🌈"), QStringLiteral("rainbow")},
    {QStringLiteral("🌂"), QStringLiteral("closed umbrella")},
    {QStringLiteral("☂️"), QStringLiteral("umbrella")},
    {QStringLiteral("☔"), QStringLiteral("umbrella with rain drops")},
    {QStringLiteral("⛱️"), QStringLiteral("umbrella on ground")},
    {QStringLiteral("⚡"), QStringLiteral("high voltage")},
    {QStringLiteral("❄️"), QStringLiteral("snowflake")},
    {QStringLiteral("☃️"), QStringLiteral("snowman")},
    {QStringLiteral("⛄"), QStringLiteral("snowman without snow")},
    {QStringLiteral("☄️"), QStringLiteral("comet")},
    {QStringLiteral("🔥"), QStringLiteral("fire")},
    {QStringLiteral("💧"), QStringLiteral("droplet")},
    {QStringLiteral("🌊"), QStringLiteral("water wave")},
    {QStringLiteral("🎃"), QStringLiteral("jack-o-lantern")},
    {QStringLiteral("🎄"), QStringLiteral("Christmas tree")},
    {QStringLiteral("🎆"), QStringLiteral("fireworks")},
    {QStringLiteral("🎇"), QStringLiteral("sparkler")},
    {QStringLiteral("🧨"), QStringLiteral("firecracker")},
    {QStringLiteral("✨"), QStringLiteral("sparkles")},
    {QStringLiteral("🎈"), QStringLiteral("balloon")},
    {QStringLiteral("🎉"), QStringLiteral("party popper")},
    {QStringLiteral("🎊"), QStringLiteral("confetti ball")},
    {QStringLiteral("🎋"), QStringLiteral("tanabata tree")},
    {QStringLiteral("🎍"), QStringLiteral("pine decoration")},
    {QStringLiteral("🎎"), QStringLiteral("Japanese dolls")},
    {QStringLiteral("🎏"), QStringLiteral("carp streamer")},
    {QStringLiteral("🎐"), QStringLiteral("wind chime")},
    {QStringLiteral("🎑"), QStringLiteral("moon viewing ceremony")},
    {QStringLiteral("🧧"), QStringLiteral("red gift envelope")},
    {QStringLiteral("🎀"), QStringLiteral("ribbon")},
    {QStringLiteral("🎁"), QStringLiteral("wrapped gift")},
    {QStringLiteral("🎗️"), QStringLiteral("reminder ribbon")},
    {QStringLiteral("🎟️"), QStringLiteral("admission tickets")},
    {QStringLiteral("🎫"), QStringLiteral("ticket")},
    {QStringLiteral("🎖️"), QStringLiteral("military medal")},
    {QStringLiteral("🏆"), QStringLiteral("trophy")},
    {QStringLiteral("🏅"), QStringLiteral("sports medal")},
    {QStringLiteral("🥇"), QStringLiteral("1st place medal")},
    {QStringLiteral("🥈"), QStringLiteral("2nd place medal")},
    {QStringLiteral("🥉"), QStringLiteral("3rd place medal")},
    {QStringLiteral("⚽"), QStringLiteral("soccer ball")},
    {QStringLiteral("⚾"), QStringLiteral("baseball")},
    {QStringLiteral("🥎"), QStringLiteral("softball")},
    {QStringLiteral("🏀"), QStringLiteral("basketball")},
    {QStringLiteral("🏐"), QStringLiteral("volleyball")},
    {QStringLiteral("🏈"), QStringLiteral("american football")},
    {QStringLiteral("🏉"), QStringLiteral("rugby football")},
    {QStringLiteral("🎾"), QStringLiteral("tennis")},
    {QStringLiteral("🥏"), QStringLiteral("flying disc")},
    {QStringLiteral("🎳"), QStringLiteral("bowling")},
    {QStringLiteral("🏏"), QStringLiteral("cricket game")},
    {QStringLiteral("🏑"), QStringLiteral("field hockey")},
    {QStringLiteral("🏒"), QStringLiteral("ice hockey")},
    {QStringLiteral("🥍"), QStringLiteral("lacrosse")},
    {QStringLiteral("🏓"), QStringLiteral("ping pong")},
    {QStringLiteral("🏸"), QStringLiteral("badminton")},
    {QStringLiteral("🥊"), QStringLiteral("boxing glove")},
    {QStringLiteral("🥋"), QStringLiteral("martial arts uniform")},
    {QStringLiteral("🥅"), QStringLiteral("goal net")},
    {QStringLiteral("⛳"), QStringLiteral("flag in hole")},
    {QStringLiteral("⛸️"), QStringLiteral("ice skate")},
    {QStringLiteral("🎣"), QStringLiteral("fishing pole")},
    {QStringLiteral("🤿"), QStringLiteral("diving mask")},
    {QStringLiteral("🎽"), QStringLiteral("running shirt")},
    {QStringLiteral("🎿"), QStringLiteral("skis")},
    {QStringLiteral("🛷"), QStringLiteral("sled")},
    {QStringLiteral("🥌"), QStringLiteral("curling stone")},
    {QStringLiteral("🎯"), QStringLiteral("direct hit")},
    {QStringLiteral("🪀"), QStringLiteral("yo-yo")},
    {QStringLiteral("🪁"), QStringLiteral("kite")},
    {QStringLiteral("🎱"), QStringLiteral("pool 8 ball")},
    {QStringLiteral("🔮"), QStringLiteral("crystal ball")},
    {QStringLiteral("🪄"), QStringLiteral("magic wand")},
    {QStringLiteral("🧿"), QStringLiteral("nazar amulet")},
    {QStringLiteral("🎮"), QStringLiteral("video game")},
    {QStringLiteral("🕹️"), QStringLiteral("joystick")},
    {QStringLiteral("🎰"), QStringLiteral("slot machine")},
    {QStringLiteral("🎲"), QStringLiteral("game die")},
    {QStringLiteral("🧩"), QStringLiteral("puzzle piece")},
    {QStringLiteral("🧸"), QStringLiteral("teddy bear")},
    {QStringLiteral("🪅"), QStringLiteral("pinata")},
    {QStringLiteral("🪆"), QStringLiteral("nesting dolls")},
    {QStringLiteral("♠️"), QStringLiteral("spade suit")},
    {QStringLiteral("♥️"), QStringLiteral("heart suit")},
    {QStringLiteral("♦️"), QStringLiteral("diamond suit")},
    {QStringLiteral("♣️"), QStringLiteral("club suit")},
    {QStringLiteral("♟️"), QStringLiteral("chess pawn")},
    {QStringLiteral("🃏"), QStringLiteral("joker")},
    {QStringLiteral("🀄"), QStringLiteral("mahjong red dragon")},
    {QStringLiteral("🎴"), QStringLiteral("flower playing cards")},
    {QStringLiteral("🎭"), QStringLiteral("performing arts")},
    {QStringLiteral("🖼️"), QStringLiteral("framed picture")},
    {QStringLiteral("🎨"), QStringLiteral("artist palette")},
    {QStringLiteral("🧵"), QStringLiteral("thread")},
    {QStringLiteral("🪡"), QStringLiteral("sewing needle")},
    {QStringLiteral("🧶"), QStringLiteral("yarn")},
    {QStringLiteral("🪢"), QStringLiteral("knot")},
    {QStringLiteral("👓"), QStringLiteral("glasses")},
    {QStringLiteral("🕶️"), QStringLiteral("sunglasses")},
    {QStringLiteral("🥽"), QStringLiteral("goggles")},
    {QStringLiteral("🥼"), QStringLiteral("lab coat")},
    {QStringLiteral("🦺"), QStringLiteral("safety vest")},
    {QStringLiteral("👔"), QStringLiteral("necktie")},
    {QStringLiteral("👕"), QStringLiteral("t-shirt")},
    {QStringLiteral("👖"), QStringLiteral("jeans")},
    {QStringLiteral("🧣"), QStringLiteral("scarf")},
    {QStringLiteral("🧤"), QStringLiteral("gloves")},
    {QStringLiteral("🧥"), QStringLiteral("coat")},
    {QStringLiteral("🧦"), QStringLiteral("socks")},
    {QStringLiteral("👗"), QStringLiteral("dress")},
    {QStringLiteral("👘"), QStringLiteral("kimono")},
    {QStringLiteral("🥻"), QStringLiteral("sari")},
    {QStringLiteral("🩱"), QStringLiteral("one-piece swimsuit")},
    {QStringLiteral("🩲"), QStringLiteral("briefs")},
    {QStringLiteral("🩳"), QStringLiteral("shorts")},
    {QStringLiteral("👙"), QStringLiteral("bikini")},
    {QStringLiteral("👚"), QStringLiteral("woman's clothes")},
    {QStringLiteral("👛"), QStringLiteral("purse")},
    {QStringLiteral("👜"), QStringLiteral("handbag")},
    {QStringLiteral("🛍️"), QStringLiteral("shopping bags")},
    {QStringLiteral("🎒"), QStringLiteral("backpack")},
    {QStringLiteral("🩴"), QStringLiteral("thong sandal")},
    {QStringLiteral("👞"), QStringLiteral("man's shoe")},
    {QStringLiteral("👟"), QStringLiteral("running shoe")},
    {QStringLiteral("🥾"), QStringLiteral("hiking boot")},
    {QStringLiteral("🥿"), QStringLiteral("flat shoe")},
    {QStringLiteral("👠"), QStringLiteral("high-heeled shoe")},
    {QStringLiteral("👡"), QStringLiteral("woman's sandal")},
    {QStringLiteral("🩰"), QStringLiteral("ballet shoes")},
    {QStringLiteral("👢"), QStringLiteral("woman's boot")},
    {QStringLiteral("👑"), QStringLiteral("crown")},
    {QStringLiteral("👒"), QStringLiteral("woman's hat")},
    {QStringLiteral("🎩"), QStringLiteral("top hat")},
    {QStringLiteral("🎓"), QStringLiteral("graduation cap")},
    {QStringLiteral("🧢"), QStringLiteral("billed cap")},
    {QStringLiteral("🪖"), QStringLiteral("military helmet")},
    {QStringLiteral("⛑️"), QStringLiteral("rescue worker's helmet")},
    {QStringLiteral("📿"), QStringLiteral("prayer beads")},
    {QStringLiteral("💄"), QStringLiteral("lipstick")},
    {QStringLiteral("💍"), QStringLiteral("ring")},
    {QStringLiteral("💎"), QStringLiteral("gem stone")},
    {QStringLiteral("🔇"), QStringLiteral("muted speaker")},
    {QStringLiteral("🔈"), QStringLiteral("speaker low volume")},
    {QStringLiteral("🔉"), QStringLiteral("speaker medium volume")},
    {QStringLiteral("🔊"), QStringLiteral("speaker high volume")},
    {QStringLiteral("📢"), QStringLiteral("loudspeaker")},
    {QStringLiteral("📣"), QStringLiteral("megaphone")},
    {QStringLiteral("📯"), QStringLiteral("postal horn")},
    {QStringLiteral("🔔"), QStringLiteral("bell")},
    {QStringLiteral("🔕"), QStringLiteral("bell with slash")},
    {QStringLiteral("🎼"), QStringLiteral("musical score")},
    {QStringLiteral("🎵"), QStringLiteral("musical note")},
    {QStringLiteral("🎶"), QStringLiteral("musical notes")},
    {QStringLiteral("🎙️"), QStringLiteral("studio microphone")},
    {QStringLiteral("🎚️"), QStringLiteral("level slider")},
    {QStringLiteral("🎛️"), QStringLiteral("control knobs")},
    {QStringLiteral("🎤"), QStringLiteral("microphone")},
    {QStringLiteral("🎧"), QStringLiteral("headphone")},
    {QStringLiteral("📻"), QStringLiteral("radio")},
    {QStringLiteral("🎷"), QStringLiteral("saxophone")},
    {QStringLiteral("🪗"), QStringLiteral("accordion")},
    {QStringLiteral("🎸"), QStringLiteral("guitar")},
    {QStringLiteral("🎹"), QStringLiteral("musical keyboard")},
    {QStringLiteral("🎺"), QStringLiteral("trumpet")},
    {QStringLiteral("🎻"), QStringLiteral("violin")},
    {QStringLiteral("🪕"), QStringLiteral("banjo")},
    {QStringLiteral("🥁"), QStringLiteral("drum")},
    {QStringLiteral("🪘"), QStringLiteral("long drum")},
    {QStringLiteral("📱"), QStringLiteral("mobile phone")},
    {QStringLiteral("📲"), QStringLiteral("mobile phone with arrow")},
    {QStringLiteral("☎️"), QStringLiteral("telephone")},
    {QStringLiteral("📞"), QStringLiteral("telephone receiver")},
    {QStringLiteral("📟"), QStringLiteral("pager")},
    {QStringLiteral("📠"), QStringLiteral("fax machine")},
    {QStringLiteral("🔋"), QStringLiteral("battery")},
    {QStringLiteral("🪫"), QStringLiteral("low battery")},
    {QStringLiteral("🔌"), QStringLiteral("electric plug")},
    {QStringLiteral("💻"), QStringLiteral("laptop")},
    {QStringLiteral("🖥️"), QStringLiteral("desktop computer")},
    {QStringLiteral("🖨️"), QStringLiteral("printer")},
    {QStringLiteral("⌨️"), QStringLiteral("keyboard")},
    {QStringLiteral("🖱️"), QStringLiteral("computer mouse")},
    {QStringLiteral("🖲️"), QStringLiteral("trackball")},
    {QStringLiteral("💽"), QStringLiteral("computer disk")},
    {QStringLiteral("💾"), QStringLiteral("floppy disk")},
    {QStringLiteral("💿"), QStringLiteral("optical disk")},
    {QStringLiteral("📀"), QStringLiteral("dvd")},
    {QStringLiteral("🧮"), QStringLiteral("abacus")},
    {QStringLiteral("🎥"), QStringLiteral("movie camera")},
    {QStringLiteral("🎞️"), QStringLiteral("film frames")},
    {QStringLiteral("📽️"), QStringLiteral("film projector")},
    {QStringLiteral("🎬"), QStringLiteral("clapper board")},
    {QStringLiteral("📺"), QStringLiteral("television")},
    {QStringLiteral("📷"), QStringLiteral("camera")},
    {QStringLiteral("📸"), QStringLiteral("camera with flash")},
    {QStringLiteral("📹"), QStringLiteral("video camera")},
    {QStringLiteral("📼"), QStringLiteral("videocassette")},
    {QStringLiteral("🔍"), QStringLiteral("magnifying glass tilted left")},
    {QStringLiteral("🔎"), QStringLiteral("magnifying glass tilted right")},
    {QStringLiteral("🕯️"), QStringLiteral("candle")},
    {QStringLiteral("💡"), QStringLiteral("light bulb")},
    {QStringLiteral("🔦"), QStringLiteral("flashlight")},
    {QStringLiteral("🏮"), QStringLiteral("red paper lantern")},
    {QStringLiteral("🪔"), QStringLiteral("diya lamp")},
    {QStringLiteral("📔"), QStringLiteral("notebook with decorative cover")},
    {QStringLiteral("📕"), QStringLiteral("closed book")},
    {QStringLiteral("📖"), QStringLiteral("open book")},
    {QStringLiteral("📗"), QStringLiteral("green book")},
    {QStringLiteral("📘"), QStringLiteral("blue book")},
    {QStringLiteral("📙"), QStringLiteral("orange book")},
    {QStringLiteral("📚"), QStringLiteral("books")},
    {QStringLiteral("📓"), QStringLiteral("notebook")},
    {QStringLiteral("📒"), QStringLiteral("ledger")},
    {QStringLiteral("📃"), QStringLiteral("page with curl")},
    {QStringLiteral("📜"), QStringLiteral("scroll")},
    {QStringLiteral("📄"), QStringLiteral("page facing up")},
    {QStringLiteral("📰"), QStringLiteral("newspaper")},
    {QStringLiteral("🗞️"), QStringLiteral("rolled-up newspaper")},
    {QStringLiteral("📑"), QStringLiteral("bookmark tabs")},
    {QStringLiteral("🔖"), QStringLiteral("bookmark")},
    {QStringLiteral("🏷️"), QStringLiteral("label")},
    {QStringLiteral("💰"), QStringLiteral("money bag")},
    {QStringLiteral("🪙"), QStringLiteral("coin")},
    {QStringLiteral("💴"), QStringLiteral("yen banknote")},
    {QStringLiteral("💵"), QStringLiteral("dollar banknote")},
    {QStringLiteral("💶"), QStringLiteral("euro banknote")},
    {QStringLiteral("💷"), QStringLiteral("pound banknote")},
    {QStringLiteral("💸"), QStringLiteral("money with wings")},
    {QStringLiteral("💳"), QStringLiteral("credit card")},
    {QStringLiteral("🧾"), QStringLiteral("receipt")},
    {QStringLiteral("💹"), QStringLiteral("chart increasing with yen")},
    {QStringLiteral("✉️"), QStringLiteral("envelope")},
    {QStringLiteral("📧"), QStringLiteral("e-mail")},
    {QStringLiteral("📨"), QStringLiteral("incoming envelope")},
    {QStringLiteral("📩"), QStringLiteral("envelope with arrow")},
    {QStringLiteral("📤"), QStringLiteral("outbox tray")},
    {QStringLiteral("📥"), QStringLiteral("inbox tray")},
    {QStringLiteral("📦"), QStringLiteral("package")},
    {QStringLiteral("📫"), QStringLiteral("closed mailbox with raised flag")},
    {QStringLiteral("📪"), QStringLiteral("closed mailbox with lowered flag")},
    {QStringLiteral("📬"), QStringLiteral("open mailbox with raised flag")},
    {QStringLiteral("📭"), QStringLiteral("open mailbox with lowered flag")},
    {QStringLiteral("📮"), QStringLiteral("postbox")},
    {QStringLiteral("🗳️"), QStringLiteral("ballot box with ballot")},
    {QStringLiteral("✏️"), QStringLiteral("pencil")},
    {QStringLiteral("✒️"), QStringLiteral("black nib")},
    {QStringLiteral("🖋️"), QStringLiteral("fountain pen")},
    {QStringLiteral("🖊️"), QStringLiteral("pen")},
    {QStringLiteral("🖌️"), QStringLiteral("paintbrush")},
    {QStringLiteral("🖍️"), QStringLiteral("crayon")},
    {QStringLiteral("📝"), QStringLiteral("memo")},
    {QStringLiteral("💼"), QStringLiteral("briefcase")},
    {QStringLiteral("📁"), QStringLiteral("file folder")},
    {QStringLiteral("📂"), QStringLiteral("open file folder")},
    {QStringLiteral("🗂️"), QStringLiteral("card index dividers")},
    {QStringLiteral("📅"), QStringLiteral("calendar")},
    {QStringLiteral("📆"), QStringLiteral("tear-off calendar")},
    {QStringLiteral("🗒️"), QStringLiteral("spiral notepad")},
    {QStringLiteral("🗓️"), QStringLiteral("spiral calendar")},
    {QStringLiteral("📇"), QStringLiteral("card index")},
    {QStringLiteral("📈"), QStringLiteral("chart increasing")},
    {QStringLiteral("📉"), QStringLiteral("chart decreasing")},
    {QStringLiteral("📊"), QStringLiteral("bar chart")},
    {QStringLiteral("📋"), QStringLiteral("clipboard")},
    {QStringLiteral("📌"), QStringLiteral("pushpin")},
    {QStringLiteral("📍"), QStringLiteral("round pushpin")},
    {QStringLiteral("📎"), QStringLiteral("paperclip")},
    {QStringLiteral("🖇️"), QStringLiteral("linked paperclips")},
    {QStringLiteral("📏"), QStringLiteral("straight ruler")},
    {QStringLiteral("📐"), QStringLiteral("triangular ruler")},
    {QStringLiteral("✂️"), QStringLiteral("scissors")},
    {QStringLiteral("🗃️"), QStringLiteral("card file box")},
    {QStringLiteral("🗄️"), QStringLiteral("file cabinet")},
    {QStringLiteral("🗑️"), QStringLiteral("wastebasket")},
    {QStringLiteral("🔒"), QStringLiteral("locked")},
    {QStringLiteral("🔓"), QStringLiteral("unlocked")},
    {QStringLiteral("🔏"), QStringLiteral("locked with pen")},
    {QStringLiteral("🔐"), QStringLiteral("locked with key")},
    {QStringLiteral("🔑"), QStringLiteral("key")},
    {QStringLiteral("🗝️"), QStringLiteral("old key")},
    {QStringLiteral("🔨"), QStringLiteral("hammer")},
    {QStringLiteral("🪓"), QStringLiteral("axe")},
    {QStringLiteral("⛏️"), QStringLiteral("pick")},
    {QStringLiteral("⚒️"), QStringLiteral("hammer and pick")},
    {QStringLiteral("🛠️"), QStringLiteral("hammer and wrench")},
    {QStringLiteral("🗡️"), QStringLiteral("dagger")},
    {QStringLiteral("⚔️"), QStringLiteral("crossed swords")},
    {QStringLiteral("🔫"), QStringLiteral("water pistol")},
    {QStringLiteral("🪃"), QStringLiteral("boomerang")},
    {QStringLiteral("🏹"), QStringLiteral("bow and arrow")},
    {QStringLiteral("🛡️"), QStringLiteral("shield")},
    {QStringLiteral("🪚"), QStringLiteral("carpentry saw")},
    {QStringLiteral("🔧"), QStringLiteral("wrench")},
    {QStringLiteral("🪛"), QStringLiteral("screwdriver")},
    {QStringLiteral("🔩"), QStringLiteral("nut and bolt")},
    {QStringLiteral("⚙️"), QStringLiteral("gear")},
    {QStringLiteral("🗜️"), QStringLiteral("clamp")},
    {QStringLiteral("⚖️"), QStringLiteral("balance scale")},
    {QStringLiteral("🦯"), QStringLiteral("white cane")},
    {QStringLiteral("🔗"), QStringLiteral("link")},
    {QStringLiteral("⛓️"), QStringLiteral("chains")},
    {QStringLiteral("🪝"), QStringLiteral("hook")},
    {QStringLiteral("🧰"), QStringLiteral("toolbox")},
    {QStringLiteral("🧲"), QStringLiteral("magnet")},
    {QStringLiteral("🪜"), QStringLiteral("ladder")},
    {QStringLiteral("⚗️"), QStringLiteral("alembic")},
    {QStringLiteral("🧪"), QStringLiteral("test tube")},
    {QStringLiteral("🧫"), QStringLiteral("petri dish")},
    {QStringLiteral("🧬"), QStringLiteral("dna")},
    {QStringLiteral("🔬"), QStringLiteral("microscope")},
    {QStringLiteral("🔭"), QStringLiteral("telescope")},
    {QStringLiteral("📡"), QStringLiteral("satellite antenna")},
    {QStringLiteral("💉"), QStringLiteral("syringe")},
    {QStringLiteral("🩸"), QStringLiteral("drop of blood")},
    {QStringLiteral("💊"), QStringLiteral("pill")},
    {QStringLiteral("🩹"), QStringLiteral("adhesive bandage")},
    {QStringLiteral("🩼"), QStringLiteral("crutch")},
    {QStringLiteral("🩺"), QStringLiteral("stethoscope")},
    {QStringLiteral("🌡️"), QStringLiteral("thermometer")},
    {QStringLiteral("🩻"), QStringLiteral("x-ray")},
    {QStringLiteral("🚪"), QStringLiteral("door")},
    {QStringLiteral("🛗"), QStringLiteral("elevator")},
    {QStringLiteral("🪞"), QStringLiteral("mirror")},
    {QStringLiteral("🪟"), QStringLiteral("window")},
    {QStringLiteral("🛏️"), QStringLiteral("bed")},
    {QStringLiteral("🛋️"), QStringLiteral("couch and lamp")},
    {QStringLiteral("🪑"), QStringLiteral("chair")},
    {QStringLiteral("🚽"), QStringLiteral("toilet")},
    {QStringLiteral("🪠"), QStringLiteral("plunger")},
    {QStringLiteral("🚿"), QStringLiteral("shower")},
    {QStringLiteral("🛁"), QStringLiteral("bathtub")},
    {QStringLiteral("🪤"), QStringLiteral("mouse trap")},
    {QStringLiteral("🪒"), QStringLiteral("razor")},
    {QStringLiteral("🧴"), QStringLiteral("lotion bottle")},
    {QStringLiteral("🧷"), QStringLiteral("safety pin")},
    {QStringLiteral("🧹"), QStringLiteral("broom")},
    {QStringLiteral("🧺"), QStringLiteral("basket")},
    {QStringLiteral("🧻"), QStringLiteral("roll of paper")},
    {QStringLiteral("🪣"), QStringLiteral("bucket")},
    {QStringLiteral("🧼"), QStringLiteral("soap")},
    {QStringLiteral("🫧"), QStringLiteral("bubbles")},
    {QStringLiteral("🪥"), QStringLiteral("toothbrush")},
    {QStringLiteral("🧽"), QStringLiteral("sponge")},
    {QStringLiteral("🧯"), QStringLiteral("fire extinguisher")},
    {QStringLiteral("🛒"), QStringLiteral("shopping cart")},
    {QStringLiteral("🚬"), QStringLiteral("cigarette")},
    {QStringLiteral("⚰️"), QStringLiteral("coffin")},
    {QStringLiteral("🪦"), QStringLiteral("headstone")},
    {QStringLiteral("⚱️"), QStringLiteral("funeral urn")},
    {QStringLiteral("🗿"), QStringLiteral("moai")},
    {QStringLiteral("🪧"), QStringLiteral("placard")},
    {QStringLiteral("🪪"), QStringLiteral("identification card")},
    {QStringLiteral("🏧"), QStringLiteral("ATM sign")},
    {QStringLiteral("🚮"), QStringLiteral("litter in bin sign")},
    {QStringLiteral("🚰"), QStringLiteral("potable water")},
    {QStringLiteral("♿"), QStringLiteral("wheelchair symbol")},
    {QStringLiteral("🚹"), QStringLiteral("men's room")},
    {QStringLiteral("🚺"), QStringLiteral("women's room")},
    {QStringLiteral("🚻"), QStringLiteral("restroom")},
    {QStringLiteral("🚼"), QStringLiteral("baby symbol")},
    {QStringLiteral("🚾"), QStringLiteral("water closet")},
    {QStringLiteral("🛂"), QStringLiteral("passport control")},
    {QStringLiteral("🛃"), QStringLiteral("customs")},
    {QStringLiteral("🛄"), QStringLiteral("baggage claim")},
    {QStringLiteral("🛅"), QStringLiteral("left luggage")},
    {QStringLiteral("⚠️"), QStringLiteral("warning")},
    {QStringLiteral("🚸"), QStringLiteral("children crossing")},
    {QStringLiteral("⛔"), QStringLiteral("no entry")},
    {QStringLiteral("🚫"), QStringLiteral("prohibited")},
    {QStringLiteral("🚳"), QStringLiteral("no bicycles")},
    {QStringLiteral("🚭"), QStringLiteral("no smoking")},
    {QStringLiteral("🚯"), QStringLiteral("no littering")},
    {QStringLiteral("🚱"), QStringLiteral("non-potable water")},
    {QStringLiteral("🚷"), QStringLiteral("no pedestrians")},
    {QStringLiteral("📵"), QStringLiteral("no mobile phones")},
    {QStringLiteral("🔞"), QStringLiteral("no one under eighteen")},
    {QStringLiteral("☢️"), QStringLiteral("radioactive")},
    {QStringLiteral("☣️"), QStringLiteral("biohazard")},
    {QStringLiteral("⬆️"), QStringLiteral("up arrow")},
    {QStringLiteral("↗️"), QStringLiteral("up-right arrow")},
    {QStringLiteral("➡️"), QStringLiteral("right arrow")},
    {QStringLiteral("↘️"), QStringLiteral("down-right arrow")},
    {QStringLiteral("⬇️"), QStringLiteral("down arrow")},
    {QStringLiteral("↙️"), QStringLiteral("down-left arrow")},
    {QStringLiteral("⬅️"), QStringLiteral("left arrow")},
    {QStringLiteral("↖️"), QStringLiteral("up-left arrow")},
    {QStringLiteral("↕️"), QStringLiteral("up-down arrow")},
    {QStringLiteral("↔️"), QStringLiteral("left-right arrow")},
    {QStringLiteral("↩️"), QStringLiteral("right arrow curving left")},
    {QStringLiteral("↪️"), QStringLiteral("left arrow curving right")},
    {QStringLiteral("⤴️"), QStringLiteral("right arrow curving up")},
    {QStringLiteral("⤵️"), QStringLiteral("right arrow curving down")},
    {QStringLiteral("🔃"), QStringLiteral("clockwise vertical arrows")},
    {QStringLiteral("🔄"), QStringLiteral("counterclockwise arrows button")},
    {QStringLiteral("🔙"), QStringLiteral("BACK arrow")},
    {QStringLiteral("🔚"), QStringLiteral("END arrow")},
    {QStringLiteral("🔛"), QStringLiteral("ON! arrow")},
    {QStringLiteral("🔜"), QStringLiteral("SOON arrow")},
    {QStringLiteral("🔝"), QStringLiteral("TOP arrow")},
    {QStringLiteral("🛐"), QStringLiteral("place of worship")},
    {QStringLiteral("⚛️"), QStringLiteral("atom symbol")},
    {QStringLiteral("🕉️"), QStringLiteral("om")},
    {QStringLiteral("✡️"), QStringLiteral("star of David")},
    {QStringLiteral("☸️"), QStringLiteral("wheel of dharma")},
    {QStringLiteral("☯️"), QStringLiteral("yin yang")},
    {QStringLiteral("✝️"), QStringLiteral("latin cross")},
    {QStringLiteral("☦️"), QStringLiteral("orthodox cross")},
    {QStringLiteral("☪️"), QStringLiteral("star and crescent")},
    {QStringLiteral("☮️"), QStringLiteral("peace symbol")},
    {QStringLiteral("🕎"), QStringLiteral("menorah")},
    {QStringLiteral("🔯"), QStringLiteral("dotted six-pointed star")},
    {QStringLiteral("♈"), QStringLiteral("Aries")},
    {QStringLiteral("♉"), QStringLiteral("Taurus")},
    {QStringLiteral("♊"), QStringLiteral("Gemini")},
    {QStringLiteral("♋"), QStringLiteral("Cancer")},
    {QStringLiteral("♌"), QStringLiteral("Leo")},
    {QStringLiteral("♍"), QStringLiteral("Virgo")},
    {QStringLiteral("♎"), QStringLiteral("Libra")},
    {QStringLiteral("♏"), QStringLiteral("Scorpio")},
    {QStringLiteral("♐"), QStringLiteral("Sagittarius")},
    {QStringLiteral("♑"), QStringLiteral("Capricorn")},
    {QStringLiteral("♒"), QStringLiteral("Aquarius")},
    {QStringLiteral("♓"), QStringLiteral("Pisces")},
    {QStringLiteral("⛎"), QStringLiteral("Ophiuchus")},
    {QStringLiteral("🔀"), QStringLiteral("shuffle tracks button")},
    {QStringLiteral("🔁"), QStringLiteral("repeat button")},
    {QStringLiteral("🔂"), QStringLiteral("repeat single button")},
    {QStringLiteral("▶️"), QStringLiteral("play button")},
    {QStringLiteral("⏩"), QStringLiteral("fast-forward button")},
    {QStringLiteral("⏭️"), QStringLiteral("next track button")},
    {QStringLiteral("⏯️"), QStringLiteral("play or pause button")},
    {QStringLiteral("◀️"), QStringLiteral("reverse button")},
    {QStringLiteral("⏪"), QStringLiteral("fast reverse button")},
    {QStringLiteral("⏮️"), QStringLiteral("last track button")},
    {QStringLiteral("🔼"), QStringLiteral("upwards button")},
    {QStringLiteral("⏫"), QStringLiteral("fast up button")},
    {QStringLiteral("🔽"), QStringLiteral("downwards button")},
    {QStringLiteral("⏬"), QStringLiteral("fast down button")},
    {QStringLiteral("⏸️"), QStringLiteral("pause button")},
    {QStringLiteral("⏹️"), QStringLiteral("stop button")},
    {QStringLiteral("⏺️"), QStringLiteral("record button")},
    {QStringLiteral("⏏️"), QStringLiteral("eject button")},
    {QStringLiteral("🎦"), QStringLiteral("cinema")},
    {QStringLiteral("🔅"), QStringLiteral("dim button")},
    {QStringLiteral("🔆"), QStringLiteral("bright button")},
    {QStringLiteral("📶"), QStringLiteral("antenna bars")},
    {QStringLiteral("📳"), QStringLiteral("vibration mode")},
    {QStringLiteral("📴"), QStringLiteral("mobile phone off")},
    {QStringLiteral("♀️"), QStringLiteral("female sign")},
    {QStringLiteral("♂️"), QStringLiteral("male sign")},
    {QStringLiteral("⚧️"), QStringLiteral("transgender symbol")},
    {QStringLiteral("✖️"), QStringLiteral("multiply")},
    {QStringLiteral("➕"), QStringLiteral("plus")},
    {QStringLiteral("➖"), QStringLiteral("minus")},
    {QStringLiteral("➗"), QStringLiteral("divide")},
    {QStringLiteral("🟰"), QStringLiteral("heavy equals sign")},
    {QStringLiteral("♾️"), QStringLiteral("infinity")},
    {QStringLiteral("‼️"), QStringLiteral("double exclamation mark")},
    {QStringLiteral("⁉️"), QStringLiteral("exclamation question mark")},
    {QStringLiteral("❓"), QStringLiteral("question mark")},
    {QStringLiteral("❔"), QStringLiteral("white question mark")},
    {QStringLiteral("❕"), QStringLiteral("white exclamation mark")},
    {QStringLiteral("❗"), QStringLiteral("exclamation mark")},
    {QStringLiteral("〰️"), QStringLiteral("wavy dash")},
    {QStringLiteral("💱"), QStringLiteral("currency exchange")},
    {QStringLiteral("💲"), QStringLiteral("heavy dollar sign")},
    {QStringLiteral("⚕️"), QStringLiteral("medical symbol")},
    {QStringLiteral("♻️"), QStringLiteral("recycling symbol")},
    {QStringLiteral("⚜️"), QStringLiteral("fleur-de-lis")},
    {QStringLiteral("🔱"), QStringLiteral("trident emblem")},
    {QStringLiteral("📛"), QStringLiteral("name badge")},
    {QStringLiteral("🔰"), QStringLiteral("Japanese symbol for beginner")},
    {QStringLiteral("⭕"), QStringLiteral("hollow red circle")},
    {QStringLiteral("✅"), QStringLiteral("check mark button")},
    {QStringLiteral("☑️"), QStringLiteral("check box with check")},
    {QStringLiteral("✔️"), QStringLiteral("check mark")},
    {QStringLiteral("❌"), QStringLiteral("cross mark")},
    {QStringLiteral("❎"), QStringLiteral("cross mark button")},
    {QStringLiteral("➰"), QStringLiteral("curly loop")},
    {QStringLiteral("➿"), QStringLiteral("double curly loop")},
    {QStringLiteral("〽️"), QStringLiteral("part alternation mark")},
    {QStringLiteral("✳️"), QStringLiteral("eight-spoked asterisk")},
    {QStringLiteral("✴️"), QStringLiteral("eight-pointed star")},
    {QStringLiteral("❇️"), QStringLiteral("sparkle")},
    {QStringLiteral("©️"), QStringLiteral("copyright")},
    {QStringLiteral("®️"), QStringLiteral("registered")},
    {QStringLiteral("™️"), QStringLiteral("trade mark")},
    {QStringLiteral("#️⃣"), QStringLiteral("keycap number sign")},
    {QStringLiteral("*️⃣"), QStringLiteral("keycap asterisk")},
    {QStringLiteral("0️⃣"), QStringLiteral("keycap 0")},
    {QStringLiteral("1️⃣"), QStringLiteral("keycap 1")},
    {QStringLiteral("2️⃣"), QStringLiteral("keycap 2")},
    {QStringLiteral("3️⃣"), QStringLiteral("keycap 3")},
    {QStringLiteral("4️⃣"), QStringLiteral("keycap 4")},
    {QStringLiteral("5️⃣"), QStringLiteral("keycap 5")},
    {QStringLiteral("6️⃣"), QStringLiteral("keycap 6")},
    {QStringLiteral("7️⃣"), QStringLiteral("keycap 7")},
    {QStringLiteral("8️⃣"), QStringLiteral("keycap 8")},
    {QStringLiteral("9️⃣"), QStringLiteral("keycap 9")},
    {QStringLiteral("🔟"), QStringLiteral("keycap 10")},
    {QStringLiteral("🔠"), QStringLiteral("input latin uppercase")},
    {QStringLiteral("🔡"), QStringLiteral("input latin lowercase")},
    {QStringLiteral("🔢"), QStringLiteral("input numbers")},
    {QStringLiteral("🔣"), QStringLiteral("input symbols")},
    {QStringLiteral("🔤"), QStringLiteral("input latin letters")},
    {QStringLiteral("🅰️"), QStringLiteral("A button blood type")},
    {QStringLiteral("🆎"), QStringLiteral("AB button blood type")},
    {QStringLiteral("🅱️"), QStringLiteral("B button blood type")},
    {QStringLiteral("🆑"), QStringLiteral("CL button")},
    {QStringLiteral("🆒"), QStringLiteral("COOL button")},
    {QStringLiteral("🆓"), QStringLiteral("FREE button")},
    {QStringLiteral("ℹ️"), QStringLiteral("information")},
    {QStringLiteral("🆔"), QStringLiteral("ID button")},
    {QStringLiteral("Ⓜ️"), QStringLiteral("circled M")},
    {QStringLiteral("🆕"), QStringLiteral("NEW button")},
    {QStringLiteral("🆖"), QStringLiteral("NG button")},
    {QStringLiteral("🅾️"), QStringLiteral("O button blood type")},
    {QStringLiteral("🆗"), QStringLiteral("OK button")},
    {QStringLiteral("🅿️"), QStringLiteral("P button")},
    {QStringLiteral("🆘"), QStringLiteral("SOS button")},
    {QStringLiteral("🆙"), QStringLiteral("UP! button")},
    {QStringLiteral("🆚"), QStringLiteral("VS button")},
    {QStringLiteral("🈁"), QStringLiteral("Japanese here button")},
    {QStringLiteral("🈂️"), QStringLiteral("Japanese service charge button")},
    {QStringLiteral("🈷️"), QStringLiteral("Japanese monthly amount button")},
    {QStringLiteral("🈶"), QStringLiteral("Japanese not free of charge button")},
    {QStringLiteral("🈯"), QStringLiteral("Japanese reserved button")},
    {QStringLiteral("🉐"), QStringLiteral("Japanese bargain button")},
    {QStringLiteral("🈹"), QStringLiteral("Japanese discount button")},
    {QStringLiteral("🈚"), QStringLiteral("Japanese free of charge button")},
    {QStringLiteral("🈲"), QStringLiteral("Japanese prohibited button")},
    {QStringLiteral("🉑"), QStringLiteral("Japanese acceptable button")},
    {QStringLiteral("🈸"), QStringLiteral("Japanese application button")},
    {QStringLiteral("🈴"), QStringLiteral("Japanese passing grade button")},
    {QStringLiteral("🈳"), QStringLiteral("Japanese vacancy button")},
    {QStringLiteral("㊗️"), QStringLiteral("Japanese congratulations button")},
    {QStringLiteral("㊙️"), QStringLiteral("Japanese secret button")},
    {QStringLiteral("🈺"), QStringLiteral("Japanese open for business button")},
    {QStringLiteral("🈵"), QStringLiteral("Japanese no vacancy button")},
    {QStringLiteral("🔴"), QStringLiteral("red circle")},
    {QStringLiteral("🟠"), QStringLiteral("orange circle")},
    {QStringLiteral("🟡"), QStringLiteral("yellow circle")},
    {QStringLiteral("🟢"), QStringLiteral("green circle")},
    {QStringLiteral("🔵"), QStringLiteral("blue circle")},
    {QStringLiteral("🟣"), QStringLiteral("purple circle")},
    {QStringLiteral("🟤"), QStringLiteral("brown circle")},
    {QStringLiteral("⚫"), QStringLiteral("black circle")},
    {QStringLiteral("⚪"), QStringLiteral("white circle")},
    {QStringLiteral("🟥"), QStringLiteral("red square")},
    {QStringLiteral("🟧"), QStringLiteral("orange square")},
    {QStringLiteral("🟨"), QStringLiteral("yellow square")},
    {QStringLiteral("🟩"), QStringLiteral("green square")},
    {QStringLiteral("🟦"), QStringLiteral("blue square")},
    {QStringLiteral("🟪"), QStringLiteral("purple square")},
    {QStringLiteral("🟫"), QStringLiteral("brown square")},
    {QStringLiteral("⬛"), QStringLiteral("black large square")},
    {QStringLiteral("⬜"), QStringLiteral("white large square")},
    {QStringLiteral("◼️"), QStringLiteral("black medium square")},
    {QStringLiteral("◻️"), QStringLiteral("white medium square")},
    {QStringLiteral("◾"), QStringLiteral("black medium-small square")},
    {QStringLiteral("◽"), QStringLiteral("white medium-small square")},
    {QStringLiteral("▪️"), QStringLiteral("black small square")},
    {QStringLiteral("▫️"), QStringLiteral("white small square")},
    {QStringLiteral("🔶"), QStringLiteral("large orange diamond")},
    {QStringLiteral("🔷"), QStringLiteral("large blue diamond")},
    {QStringLiteral("🔸"), QStringLiteral("small orange diamond")},
    {QStringLiteral("🔹"), QStringLiteral("small blue diamond")},
    {QStringLiteral("🔺"), QStringLiteral("red triangle pointed up")},
    {QStringLiteral("🔻"), QStringLiteral("red triangle pointed down")},
    {QStringLiteral("💠"), QStringLiteral("diamond with a dot")},
    {QStringLiteral("🔘"), QStringLiteral("radio button")},
    {QStringLiteral("🔳"), QStringLiteral("white square button")},
    {QStringLiteral("🔲"), QStringLiteral("black square button")},
    {QStringLiteral("🏁"), QStringLiteral("chequered flag")},
    {QStringLiteral("🚩"), QStringLiteral("triangular flag")},
    {QStringLiteral("🎌"), QStringLiteral("crossed flags")},
    {QStringLiteral("🏴"), QStringLiteral("black flag")},
    {QStringLiteral("🏳️"), QStringLiteral("white flag")},
    {QStringLiteral("🏳️‍🌈"), QStringLiteral("rainbow flag")},
    {QStringLiteral("🏳️‍⚧️"), QStringLiteral("transgender flag")},
    {QStringLiteral("🏴‍☠️"), QStringLiteral("pirate flag")},
    {QStringLiteral("🇦🇨"), QStringLiteral("flag Ascension Island")},
};
